### ISSUE TITLE
not up to date anymore :(targets,yosemite)

### ISSUE THREAD

**Issue by gcmartijn** [Russell-King/SubMonkey#2]
H!

I want to use Sublime Text 3 using yosemite so I follow your instructions but it keeps saying:
[Errno 2] No such file or directory: 'transcc_macos'
[cmd: ['transcc_macos', '-target=Desktop_Game', '-run', '""']]
[dir: /Applications/Sublime Text.app/Contents/MacOS]
[path: /usr/bin:/bin:/usr/sbin:/sbin]
[Finished]

But its in the $PATH, when I do this
gcmartijns-Mac-Pro:~ gcmartijn$ echo $PATH
/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/MonkeyXPro/bin

- The sublime project is on a NAS disk, but I think that is oke.

Then there is a small update using the (new) valid targets
The Glfw2/3 for example, they are not in the sublime target list.

gcmartijns-Mac-Pro:~ gcmartijn$ transcc_macos
TRANS monkey compiler V1.77
TRANS Usage: transcc [-update] [-build] [-run] [-clean] [-config=...] [-target=...] [-cfgfile=...] [-modpath=...] <main_monkey_source_file>
Valid targets: C++_Tool Desktop_Game_(Glfw2) Desktop_Game_(Glfw3) Html5_Game iOS_Game

**Comment by Russell-King** [comment]
Sadly, I've let this project and my Monkey work fall to the side as other things in life took over :(

Yosemite might be what is throwing the wrench in there. I've not kept up to date on any changes that might affect Monkey or updates to monkey in general. I'll look into it though and try to find a solution and update the package :)

**Comment by gcmartijn** [comment]
Cool, there is a file with all the product updates inside monkey.
But that will cost you to much time.

**Comment by gcmartijn** [comment]
I found a up to date osx alternative ;) http://www.grudlux.com/mollusk/ so I close this issue.

**Comment by Russell-King** [comment]
Good to hear, Mollusk is a good little IDE. :)

Sorry I couldn't get things back up and running to test out Mac builds very fast. Got a Yosemite VM built to test my own install instructions out and such. I'll still look into making sure the package is working right. 

I'm using this as a convenient excuse to get back into Monkey though =P

**Comment by gcmartijn** [comment]
my exuse is searching for a good ide, and not creating games ;)
Op 5 feb. 2015 13:03 schreef "Russell E. King III" <notifications@github.com

**Comment by Russell-King** [comment]
Found a workaround for the build issue. After a rather lengthy spiral down the google search hole, I found that Apple changed the way environmental variables are accessed by GUI applications in Yosemite and have made it a huge pain to actually get them working now(in my Mac newbie eyes, at least). 

I'll update the package with the workaround tomorrow after I get some sleep, but I went ahead and made a file linked below that should fix yours right away if you want. Just save it to the User folder in Packages(Sublime text > Preferences > Browse Packages...) and restart Sublime Text. When you are ready to build just make sure to select the new system under Tools :)

https://dl.dropboxusercontent.com/u/1348869/Monkey%20-%20OSX%20-%20Yosemite%20.sublime-build

**Comment by gcmartijn** [comment]
Its working I manual changed the target to this:
"cmd": ["transcc_macos", "-target=Desktop_Game_(Glfw2)", "-run", "\"$file\""]

Going to work with sublime again :)

**Comment by Russell-King** [comment]
For now that will only work for the desktop build, but it's easy enough to fix in the other files if you want to try them out as well. Just copy and paste the "path" line to the OSX section of each build file(found in installed packages, just open it with). 

Kind of a brute force tactic because of Apple's odd decisions with Yosemite, but it works for now :)
